#!/usr/bin/env python3
"""Fill cards.example with hand-authored Lebanese usage sentences.

Match strategy:
    1. Find the first Arabic line in the card (front or back).
    2. Look it up in EXAMPLES (exact, harakat-stripped, ±definite article).
    3. Write the example into cards.example.

EXAMPLES is keyed by the Arabic head-form, valued by a three-line string:
<arabic sentence>\\n<lebanese chat-alphabet>\\n<english>. Idempotent —
only fills NULL cells.

Run:
  python3 .claude/skills/deck-builder/fill_examples.py deck.lapse
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

ARABIC_RE = re.compile(r"[؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]+")


def first_arabic_token(text: str | None) -> str | None:
    if not text:
        return None
    for line in text.split("\n"):
        line = line.strip()
        if line and ARABIC_RE.search(line):
            return line.rstrip("؟?!.,،")
    return None


# Lebanese chat-alphabet:  2=ق  7=ح  9=ص  6=ط  3=ع  gh=غ  kh=خ  sh=ش
# b- = imperfect indicative ("I do"), 3am- = continuous, ra7- = future,
# kaan = past auxiliary.
EXAMPLES: dict[str, str] = {
    # ---------- Greetings / politeness ----------
    "مرحبا": "مرحبا، كيفك اليوم؟\nMar7aba, kifak el-yom?\nHello, how are you today?",
    "أهلا": "أهلا وسهلا، تفضل\nAhla w sahla, tfaDDal\nWelcome, come in",
    "أهلين": "أهلين! كيف الأحوال؟\nAhlayn! Kif el-a7waal?\nHi! How's everything?",
    "شكراً": "شكراً كتير لمساعدتك\nShukran kteer la-musa3adtak\nThanks a lot for your help",
    "عفواً": "عفواً، ما في مشكلة\n3afwan, ma fi mishkleh\nYou're welcome, no problem",
    "آسف": "آسف، ما كان قصدي\nAasef, ma kaan a9di\nSorry, I didn't mean to",
    "معلش": "معلش، بتصير\nMa3lesh, btsiir\nNo worries, it happens",

    # ---------- Yes/no/basics ----------
    "نعم": "نعم، بدي ساعدك\nNa3am, baddi saa3dak\nYes, I want to help you",
    "لا": "لا، ما بقدر هلق\nLa, ma b2der halla2\nNo, I can't right now",
    "آه": "آه، فهمت عليك\nAah, fhemet 3alayk\nYeah, I understood you",

    # ---------- Question words ----------
    "شو": "شو عم تعمل؟\nShu 3am ta3mel?\nWhat are you doing?",
    "وين": "وين كنت مبارح؟\nWen kenet mbaare7?\nWhere were you yesterday?",
    "متى": "متى منلتقي؟\nMata mnelta2i?\nWhen do we meet?",
    "كيف": "كيف بدنا نروح؟\nKif badna nrou7?\nHow are we going to go?",
    "ليش": "ليش متأخر؟\nLeesh mit2akhkhar?\nWhy are you late?",
    "مين": "مين بالباب؟\nMeen bel-baab?\nWho's at the door?",

    # ---------- Pronouns / connectors ----------
    "احنا": "احنا رايحين عالبيت\nNi7na raay7iin 3al-bayt\nWe are going home",
    "و": "إجا أحمد وسامي\nIja A7mad w Saami\nAhmad and Sami came",
    "بس": "بدي روح، بس تعبان\nBaddi rou7, bas ta3baan\nI want to go, but I'm tired",
    "أو": "بدك قهوة أو شاي؟\nBaddak ahweh aw shay?\nDo you want coffee or tea?",
    "فَ": "خلصت الشغل، فرحت\nKhala9et esh-shighl, fa-re7et\nI finished work, so I left",
    "إذا": "إذا بدك، منروح سوا\nIza baddak, mnrou7 sawa\nIf you want, we'll go together",
    "حتى": "ما رد حتى السا‏عة عشرة\nMa radd 7atta es-saa3a 3ashra\nHe didn't reply even until ten",
    "لمّا": "لمّا تجي، بحكيك\nLamma teji, b7akiik\nWhen you come, I'll talk to you",
    "إنّه": "قال إنّه تأخّر\n2aal inno t2akhkhar\nHe said that he was late",
    "إلّي": "هاد الكتاب اللي حبّيته\nHaad el-kteb illi 7abbayto\nThis is the book that I liked",
    "عشان": "ما طلعت عشان البرد\nMa Tle3et 3ashaan el-bard\nI didn't go out because of the cold",
    "لإنّه": "تأخّر لإنّه كان مشغول\nT2akhkhar la-inno kaan mashghuul\nHe was late because he was busy",
    "لحتّى": "إنطرني لحتّى أرجع\nInTorni la-7atta erja3\nWait until I come back",

    # ---------- Quantity / qualifiers ----------
    "كتير": "في ناس كتير هون\nFi naas kteer hon\nThere are a lot of people here",
    "شوي": "إنطرني شوي\nInTorni shway\nWait for me a bit",
    "قليل": "في قليل ملح\nFi 2aliil meleh\nThere's a little salt",
    "كل": "كل يوم بدرس عربي\nKell yom bedres 3arabi\nI study Arabic every day",
    "أي": "أي شي بدك\nAyy shi baddak\nAnything you want",
    "بسّ": "بسّ هيدا اللي عندي\nBass hayda elli 3indi\nThat's all I have",

    # ---------- Verbs (general) ----------
    "قبل": "قبل العرض من الشركة\n2ibil el-3arD min esh-shirkeh\nHe accepted the offer from the company",
    "نصح": "نصحني آخد إجازة\nNa9a7ni aakhod ijaazeh\nHe advised me to take a break",
    "وافق": "وافقت على المشروع\nWaaf2et 3ala el-mashruu3\nI agreed to the project",
    "أعلن": "أعلنوا الفوز اليوم\nA3lanu el-fawz el-yom\nThey announced the win today",
    "أزعج": "أزعجني الصوت العالي\nAz3ajni e9-9ot el-3aali\nThe loud noise annoyed me",
    "جاوب": "ما جاوبتني على السؤال\nMa jaawabtni 3al-su2aal\nYou didn't answer my question",
    "رد": "ما رد على التلفون\nMa radd 3at-telefoon\nHe didn't answer the phone",
    "اعتذر": "اعتذرت منه عالغلطة\nI3tazaret menno 3al-ghalTa\nI apologized to him for the mistake",
    "وصل": "وصلت متأخرة عالاجتماع\nW9elet mit2akhra 3al-ijtimaa3\nShe arrived late to the meeting",
    "سأل": "سألني مين أنا\nSa2alni meen ana\nHe asked me who I am",
    "طلب": "طلبت قهوة بحليب\nTalabet ahweh bi-7aliib\nI ordered coffee with milk",
    "تجنّب": "تجنّبت الموضوع\nTjannabet el-mawDuu3\nI avoided the topic",
    "كان": "كان عندي اجتماع\nKaan 3indi ijtimaa3\nI had a meeting",
    "قدر": "ما قدرت آجي\nMa 2deret eji\nI couldn't come",
    "غار": "غار من نجاحه\nGhaar min najaa7o\nHe got jealous of his success",
    "صار": "صار يحكي عربي منيح\n9aar ye7ki 3arabi mneeh\nHe started speaking Arabic well",
    "ترجّى": "ترجّاني آجي\nTrajjaani eji\nHe begged me to come",
    "خان": "خانتو ثقتو\nKhaanto thi2to\nShe betrayed his trust",
    "جاب": "جاب معه هدية\nJaab ma3o hadiyyeh\nHe brought a gift with him",
    "بنى": "بنيت بيت جديد\nBanayt bayt jdiid\nI built a new house",
    "اشترى": "اشتريت كتاب جديد\nEshtarayt kteb jdiid\nI bought a new book",
    "رنّ": "رنّ التلفون مرتين\nRann et-telefoon marrtayn\nThe phone rang twice",
    "سمّى": "سمّوا الولد كريم\nSammu el-walad Kariim\nThey named the boy Karim",
    "هدي": "هدّي حالك شوي\nHaddi 7aalak shway\nCalm yourself down a bit",
    "لغى": "لغوا الرحلة\nLaghu er-re7leh\nThey canceled the trip",
    "اهتمّ": "اهتمّ بصحتك\nIhtamm bi-9e7tak\nTake care of your health",
    "حمل": "حملت الشنطة لحالي\n7emelet esh-shanTa la-7aali\nI carried the bag by myself",
    "شيّك": "شيّك على الإيميل\nShayyek 3al-email\nCheck the email",
    "اختار": "اختار اللون الأزرق\nIkhtaar el-loon el-azra2\nHe chose the blue color",
    "نظّف": "نظّفت الغرفة\nNaDHDHafet el-ghurfeh\nI cleaned the room",
    "إجا": "إجا يزورني الصبح\nIja yzuurni e9-9eb7\nHe came to visit me in the morning",
    "سكّر": "سكّر الباب بهدوء\nSakker el-baab bi-hudoo2\nClose the door quietly",
    "قارن": "قارنت الأسعار\n2aaranet el-as3aar\nI compared the prices",
    "شكى": "شكي من الحر\nShaka min el-7arr\nHe complained about the heat",
    "كمّل": "كمّل شغلك\nKammel shighlak\nFinish your work",
    "استنتج": "استنتجت إنّه كذب\nIstantajet inno kazab\nI deduced that he lied",
    "اعتبر": "بعتبرك صديق\nB3etbrak 9adii2\nI consider you a friend",
    "ضلّ": "ضلّ يحكي ساعة\nDall ye7ki saa3a\nHe kept talking for an hour",
    "قنع": "قنعتو يجي\n2na3to yeji\nI convinced him to come",
    "كلّف": "كلّفني مية دولار\nKallafni miyyit dolar\nIt cost me a hundred dollars",
    "قحّ": "عم يقحّ كتير\n3am yqe77 kteer\nHe's coughing a lot",
    "عدّ": "عدّ الناس\n3idd en-naas\nCount the people",
    "بكي": "البنت بكت\nEl-bint bekyet\nThe girl cried",
    "رقص": "رقصنا كل الليلة\nRa2a9na kell el-layleh\nWe danced all night",
    "قرّر": "قرّرت أسافر\n2arrart saafer\nI decided to travel",
    "نكر": "نكر اللي قاله\nNakar elli 2aalo\nHe denied what he said",
    "استاهل": "هو ما بستاهل\nHowwe ma byestaahel\nHe doesn't deserve it",
    "مات": "ماتت قطّتنا الصغيرة\nMaaTet 2eTTetna e9-9ghiir\nOur little cat died",
    "ناقش": "ناقشنا الموضوع طويل\nNaa2ashna el-mawDuu3 Tawiil\nWe discussed the topic at length",
    "قسم": "قسم الفاتورة بيناتنا\n2asam el-faatuura baynaatna\nHe split the bill between us",
    "عمل": "شو عملت اليوم؟\nShu 3melet el-yom?\nWhat did you do today?",
    "سوّى": "سوّى ساندويش\nSawwa sandweesh\nHe made a sandwich",
    "جلى": "جليت الصحون\nJalayt e9-9huun\nI did the dishes",
    "رسم": "البنت رسمت قلب\nEl-bint rasamet 2alb\nThe girl drew a heart",
    "شرب": "بشرب مي كتير\nBeshrab mayy kteer\nI drink a lot of water",
    "ساق": "ساق السيارة\nSaa2 es-sayyaara\nHe drove the car",
    "أكل": "أكلت تبولة\nAkalet tabbouleh\nI ate tabbouleh",
    "فطر": "فطرنا مع بعض\nFTorna ma3 ba3D\nWe had breakfast together",
    "دخل": "دخل بدون طرق الباب\nDakhal bidun Tar2 el-baab\nHe entered without knocking",
    "فات": "فات على الشغل بدري\nFaat 3ash-shighl badri\nHe went to work early",
    "توقّع": "توقّعت إنّه ييجي\nTwa22a3et inno yeji\nI expected him to come",
    "واجه": "واجه المشكلة\nWaajah el-mushkleh\nHe faced the problem",
    "صام": "بصوم رمضان\nB9oom Ramadaan\nI fast in Ramadan",
    "خاف": "خاف من الكلب\nKhaaf min el-kalb\nHe was afraid of the dog",
    "لقى": "لقيت مفتاحي\nL2eet mufte7i\nI found my key",
    "خلص": "خلصت الواجب\nKhalla9et el-waajeb\nI finished the homework",
    "صلّح": "صلّح السيارة\n9alla7 es-sayyaara\nHe repaired the car",
    "ركّز": "ركّز معي شوي\nRakkez ma3i shway\nFocus with me a bit",
    "تابع": "بتابع المسلسل\nBtaabe3 el-musalsal\nI'm following the TV series",
    "نسي": "نسيت اسمو\nNeset esmo\nI forgot his name",
    "أخد": "أخد إجازة طويلة\nAkhad ijaazeh Tawiileh\nHe took a long vacation",
    "تحمّس": "تحمّس للسفر\nT7ammas la-s-safar\nHe got excited for the trip",
    "جاع": "جعت كتير\nJe3et kteer\nI got very hungry",
    "تعب": "تعبت من الشغل\nTe3ebet min esh-shighl\nI got tired from work",
    "أعطى": "أعطاني هدية\nA3Taani hadiyyeh\nHe gave me a gift",
    "راح": "رحت عالسوق\nRe7et 3as-soo2\nI went to the market",
    "نزل": "نزل من الباص\nNezel min el-baa9\nHe got off the bus",
    "شوى": "شوى لحمة عالفحم\nShawa la7meh 3al-fa7m\nHe grilled meat on charcoal",
    "سمع": "سمعت أغنية حلوة\nSme3et oghniyyeh 7elwe\nI heard a nice song",
    "احتاج": "بحتاج مساعدتك\nB7taaj musaa3adtak\nI need your help",
    "لاحظ": "لاحظت غلطة\nLaa7aDHet ghalTa\nI noticed a mistake",
    "عرض": "عرض عليّ فكرة\n3araD 3layy fikra\nHe offered me an idea",
    "فتح": "فتح الشباك\nFata7 esh-shibbaak\nHe opened the window",
    "دفع": "دفعت الحساب\nDfa3et el-7isaab\nI paid the bill",
    "لعب": "لعبنا كرة قدم\nLe3ebna kuret 2adam\nWe played football",
    "أجّل": "أجّلت الاجتماع\nAjjalet el-ijtimaa3\nI postponed the meeting",
    "تدرّب": "بتدرّب كل صبح\nBatdarrab kell 9eb7\nI train every morning",
    "جهّز": "جهّزت الأكل\nJahhazet el-akel\nI prepared the food",
    "قدّم": "قدّمت طلب\n2addamet Talab\nI submitted a request",
    "كبس": "كبست عالزر\nKabasit 3az-zerr\nI pressed the button",
    "وعد": "وعدني يساعدني\nWa3adni ysaa3edni\nHe promised to help me",
    "حطّ": "حطّيت الكتاب عالطاولة\n7aTTayt el-kteb 3aT-Taawleh\nI put the book on the table",
    "قرأ": "قريت كتاب جديد\n2reet kteb jdiid\nI read a new book",
    "رفض": "رفض العرض\nRafaD el-3arD\nHe refused the offer",
    "ندم": "ندمت على القرار\nNdemet 3al-2araar\nI regretted the decision",
    "تذكّر": "ما بتذكّر اسمو\nMa batdhakkar esmo\nI don't remember his name",
    "شال": "شال الشنطة\nShaal esh-shanTa\nHe carried the bag",
    "استأجر": "استأجرت شقة\nIsta2jaret sha22a\nI rented an apartment",
    "عاد": "عاد عالبيت\n3aad 3al-bayt\nHe came back home",
    "حجز": "حجزت طاولة للعشا\n7ajazet Taawleh lal-3asha\nI booked a table for dinner",
    "رجع": "رجع متأخر\nRiji3 mit2akhkhar\nHe came back late",
    "ركب": "ركب الباص\nRikeb el-baa9\nHe got on the bus",
    "ركض": "ركضنا عالملعب\nRkeDna 3al-mal3ab\nWe ran on the field",
    "حكى": "حكاني قصّة طويلة\n7akaani 2i99a Tawiileh\nHe told me a long story",
    "قال": "قال إنّه آسف\n2aal inno aasef\nHe said that he's sorry",
    "شاف": "شفت فلم منيح\nShifet filim mneeh\nI saw a good movie",
    "بعت": "بعتلك الإيميل\nBa3etlak el-email\nI sent you the email",
    "ودّى": "ودّاني عالمطار\nWaddaani 3al-maTaar\nHe took me to the airport",
    "فرجى": "فرجاني الصور\nFarjaani e9-9uwar\nHe showed me the photos",
    "غنّى": "غنّت أغنية حلوة\nGhannet oghniyyeh 7elwe\nShe sang a nice song",
    "قاعد": "قاعد بالبيت\n2aa3ed bel-bayt\nI'm sitting at home",
    "نام": "نمت بكير\nNemet bekkeer\nI slept early",
    "شمّ": "شم ريحة قهوة\nShamm rii7et ahweh\nHe smelled coffee",
    "صرف": "صرفت كل المصاري\n9arafet kell el-ma9aari\nI spent all the money",
    "وفّر": "بدي وفّر شوي\nBaddi waffer shway\nI want to save a little",
    "وقف": "وقف بالباب\nWi2if bel-baab\nHe stood at the door",
    "بلّش": "بلّشت أدرس\nBallashet edres\nI started studying",
    "وقّف": "وقّف السيارة\nWa22af es-sayyaara\nHe stopped the car",
    "سرق": "سرقوا سيارته\nSara2u sayyaarto\nThey stole his car",
    "درس": "درست عربي سنتين\nDaraset 3arabi sentein\nI studied Arabic for two years",
    "نجح": "نجحت بالامتحان\nNja7et bel-imti7aan\nI passed the exam",
    "اقترح": "اقترح فكرة منيحة\nE2tara7 fikra mnii7a\nHe suggested a good idea",
    "دعم": "دعمني كتير\nDa3amni kteer\nHe supported me a lot",
    "فاجأ": "فاجأني بزيارته\nFaaja2ni bi-zyaarto\nHe surprised me with his visit",
    "ظنّ": "ظنّيت إنّه راح\nDHannayt inno raa7\nI thought he left",
    "صوّر": "صوّرت الغروب\n9awwart el-ghuruub\nI photographed the sunset",
    "تحمّم": "تحمّمت قبل ما نام\nT7ammamt 2abel ma naam\nI showered before sleeping",
    "ذاق": "ذقت الأكل\nDhe2et el-akel\nI tasted the food",
    "علّم": "علّمني الحكي\n3allamni el-7aki\nHe taught me how to speak",
    "شكر": "شكرتو على هديتو\nShakarto 3ala hadiyyto\nI thanked him for his gift",
    "فكّر": "فكّرت بالموضوع\nFakkaret bel-mawDuu3\nI thought about the topic",
    "رمى": "رمى الكرة بعيد\nRama el-kura b3iid\nHe threw the ball far",
    "ربط": "ربط شعرها\nRabaT sha3rha\nHe tied her hair",
    "حوّل": "حوّلت المصاري\n7awwalet el-ma9aari\nI transferred the money",
    "ترجم": "ترجم الجملة بالإنكليزي\nTarjam el-jumleh bil-inglizi\nHe translated the sentence to English",
    "سافر": "سافرت ع باريس\nSaafart 3a Paris\nI traveled to Paris",
    "شغّل": "شغّل التلفزيون\nShaghghal et-televizyon\nHe turned on the TV",
    "فهم": "فهمت كل شي\nFhemet kell shi\nI understood everything",
    "استعمل": "استعملت قاموسي\nIsta3malet 2aamuusi\nI used my dictionary",
    "زار": "زارني خالي\nZaarni khaali\nMy uncle visited me",
    "استنّى": "استنّيتك ساعة\nIstannayetak saa3a\nI waited for you an hour",
    "صحي": "صحيت الصبح بكير\n9e7iit e9-9eb7 bekkeer\nI woke up early in the morning",
    "مشى": "مشيت كتير اليوم\nMshiit kteer el-yom\nI walked a lot today",
    "غسل": "غسلت الصحون\nGhasalet e9-9huun\nI washed the dishes",
    "حضر": "حضرت العرض\n7Drit el-3arD\nI attended the show",
    "فاز": "فازت الفرقة\nFaazet el-fer2a\nThe team won",
    "تمنّى": "تمنّى لي حظ سعيد\nTmanna lee 7aZZ sa3iid\nHe wished me good luck",
    "كتب": "كتبت رسالة\nKtabet risaaleh\nI wrote a letter",
    "نطّ": "الولد نطّ من الفرحة\nEl-walad naTT min el-far7a\nThe boy jumped for joy",
    "خلّى": "خلّى الباب مفتوح\nKhalla el-baab maftuu7\nHe left the door open",
    "باس": "باسني عالخد\nBaasni 3al-khadd\nHe kissed me on the cheek",
    "عرف": "بعرفك من زمان\nBa3rfak min zamaan\nI've known you for a while",
    "ضحك": "ضحكت كتير عالنكتة\nDe7ket kteer 3an-nukteh\nI laughed a lot at the joke",
    "تمدّد": "تمدّد عالكنبة\nTmaddad 3al-kanbeh\nHe stretched out on the couch",
    "تعلّم": "بتعلّم عربي\nBat3allam 3arabi\nI'm learning Arabic",
    "ترك": "ترك الشغل\nTarak esh-shighl\nHe left the job",
    "كذب": "ما تكذب عليّ\nMa tekzib 3layy\nDon't lie to me",
    "تطلّع": "تطلّع عالسما\nTTalla3 3as-sama\nLook at the sky",
    "دوّر": "دوّرت كتير\nDawwart kteer\nI searched a lot",
    "خسر": "خسر اللعبة\nKhiser el-le3beh\nHe lost the game",
    "ساعد": "ساعدتو كتير\nSaa3ato kteer\nI helped him a lot",
    "غلط": "غلطت بالعنوان\nGhleT bel-3inwaan\nI made a mistake in the address",
    "قصد": "قصدت أساعدك\n2a9adet saa3edak\nI meant to help you",
    "قاس": "قاس طول الطاولة\n2aas Tuul eT-Taawleh\nHe measured the table's length",
    "التقى": "التقينا بالسوق\nElta2ayna bes-soo2\nWe met at the market",
    "اشتاق": "اشتقتلك\nEshta2etlak\nI missed you",
    "خلط": "خلطت السكر بالشاي\nKhalaTet es-sukkar besh-shay\nI mixed the sugar in the tea",
    "تحرّك": "تحرّك بسرعة\nT7arrak bi-sur3a\nMove quickly",
    "حلم": "حلمت فيك مبارح\n7lemet fiik mbaare7\nI dreamed about you yesterday",
    "حبّ": "بحب أكل أمي\nB7eb akel immi\nI love my mom's food",
    "حك": "حكّيت إيدي\n7akket eedi\nI scratched my hand",
    "بدي": "بدي قهوة من فضلك\nBaddi ahweh min faDlak\nI want coffee please",
    "ممكن": "ممكن أسألك شي؟\nMumken as2alak shi?\nMay I ask you something?",
    "لازم": "لازم أروح هلق\nLaazem rou7 halla2\nI have to go now",
    "رح": "رح آجي بكرا\nRa7 eji bukra\nI'll come tomorrow",
    "مزح": "كنت عم بمزح\nKenet 3am bemzaa7\nI was joking",
    "عزم": "عزمونا عالعشا\n3azamuuna 3al-3asha\nThey invited us for dinner",
    "لام": "لامني عالغلطة\nLaamni 3al-ghalTa\nHe blamed me for the mistake",

    # ---------- Adjectives ----------
    "كبير": "هاد بيت كبير\nHaad bayt kbiir\nThis is a big house",
    "صغير": "أخي الصغير\nAkhi e9-9ghiir\nMy little brother",
    "حلو": "هاي قهوة حلوة\nHayy ahweh 7elwe\nThis is nice coffee",
    "جميل": "هاي البنت جميلة\nHayy el-bint jamiile\nThis girl is beautiful",
    "بعيد": "البيت بعيد\nEl-bayt b3iid\nThe house is far",
    "قريب": "السوق قريب\nEs-soo2 2arrayyeb\nThe market is close",
    "كافي": "هاد كافي شكراً\nHaad kaafi shukran\nThis is enough thanks",
    "متأخّر": "إجا متأخّر كالعادة\nIja mit2akhkhar kal-3aada\nHe came late as usual",
    "بسيط": "هاي مشكلة بسيطة\nHayy mishkleh basii6a\nThis is a simple problem",
    "صعب": "السؤال صعب\nEs-su2aal 9a3eb\nThe question is hard",
    "سهل": "العمل سهل\nEl-3amal sahel\nThe work is easy",
    "غالي": "هاد كتير غالي\nHaad kteer ghaali\nThis is very expensive",
    "رخيص": "لقيتو رخيص\nL2eeto rkhii9\nI found it cheap",
    "جديد": "اشتريت تلفون جديد\nEshtarayt telefoon jdiid\nI bought a new phone",
    "قديم": "هاد كتاب قديم\nHaad kteb 2adiim\nThis is an old book",
    "نظيف": "البيت نظيف\nEl-bayt nDHiif\nThe house is clean",
    "وسخ": "ثيابك وسخة\nThiyaabak wisikha\nYour clothes are dirty",
    "حر": "اليوم حر\nEl-yom 7arr\nToday it's hot",
    "بارد": "الجو بارد\nEl-jaww baared\nThe weather is cold",
    "ساخن": "القهوة ساخنة\nEl-ahweh saakhne\nThe coffee is hot",
    "تعبان": "أنا كتير تعبان\nAna kteer ta3baan\nI'm very tired",
    "مبسوط": "أنا مبسوط هون\nAna mabsuuT hon\nI'm happy here",
    "حزين": "ليش حزين؟\nLeesh 7aziin?\nWhy are you sad?",
    "مشغول": "أنا مشغول هلق\nAna mashghuul halla2\nI'm busy now",
    "فاضي": "البيت فاضي\nEl-bayt faaDiy\nThe house is empty",
    "مليان": "الكاس مليان\nEl-kaas malyaan\nThe glass is full",
    "ضعيف": "صحته ضعيفة\n9e7to D3iife\nHis health is weak",
    "قوي": "قوي بالعربي\n2awi bel-3arabi\nHe's strong in Arabic",
    "طويل": "هاد طويل كتير\nHaad Tawiil kteer\nThis is very long",
    "قصير": "اليوم نهار قصير\nEl-yom nhaar 2a9iir\nToday is a short day",
    "ثقيل": "الشنطة ثقيلة\nEsh-shanTa thqiile\nThe bag is heavy",
    "خفيف": "الكتاب خفيف\nEl-kteb khafiif\nThe book is light",
    "غني": "هو رجال غني\nHowwe rijjaal ghani\nHe's a rich man",
    "فقير": "العيلة فقيرة\nEl-3ayleh fa2iire\nThe family is poor",
    "ذكي": "هاي بنت ذكية\nHayy bint zakiyye\nThis is a smart girl",
    "غبي": "ما تكون غبي\nMa tekuun ghabiy\nDon't be stupid",
    "حقيقي": "هاد جواب حقيقي\nHaad jawaab 7a2ii2i\nThis is a real answer",
    "غريب": "هاد شي غريب\nHaad shi ghariib\nThis is a weird thing",
    "مهم": "هاد كتير مهم\nHaad kteer muhimm\nThis is very important",
    "مستحيل": "هاد مستحيل!\nHaad musta7iil!\nThis is impossible!",
    "مفيد": "هاد كتاب مفيد\nHaad kteb mufiid\nThis is a useful book",
    "آخر": "هاي آخر مرة\nHayy aakhir marra\nThis is the last time",
    "أوّل": "هاي أوّل مرة\nHayy awwal marra\nThis is the first time",
    "أحسن": "هاد أحسن من\nHaad a7san min\nThis is better than",
    "أسوأ": "اليوم أسوأ من مبارح\nEl-yom aswa2 min mbaare7\nToday is worse than yesterday",
    "موجود": "هو موجود بالبيت\nHowwe mawjuud bel-bayt\nHe's at the house",
    "ناصح": "هاد ولد ناصح\nHaad walad naa9e7\nThis is a chubby boy",
    "متزوج": "هو متزوّج من سنة\nHowwe metzawwej min seneh\nHe's been married for a year",
    "مريض": "اليوم أنا مريض\nEl-yom ana mariiD\nToday I'm sick",
    "ناجح": "هو طالب ناجح\nHowwe Taaleb naaje7\nHe's a successful student",
    "مهندس": "أبي مهندس\nAbi muhandes\nMy father is an engineer",
    "موسيقى": "بحب الموسيقى\nB7eb el-muusiiqaa\nI love music",
    "محلي": "هاد منتج محلي\nHaad muntaj ma7alli\nThis is a local product",
    "دولي": "مطار دولي\nMaTaar duwaliy\nInternational airport",
    "كامل": "اليوم كامل بشتغل\nEl-yom kaamil beshteghel\nThe whole day I work",
    "مختلف": "هاد رأي مختلف\nHaad ra2y mukhtalef\nThis is a different opinion",
    "صحيح": "هاد صحيح\nHaad 9a7ii7\nThis is correct",
    "مجنون": "هاد كتير مجنون\nHaad kteer majnuun\nThis is so crazy",
    "مزعج": "الصوت مزعج\nE9-9ot muz3ej\nThe sound is annoying",
    "متضايق": "أنا متضايق منو\nAna mitDaayi2 menno\nI'm annoyed at him",
    "زهقان": "أنا زهقان\nAna zah2aan\nI'm bored",
    "ممل": "الفلم كان ممل\nEl-filim kaan mumill\nThe movie was boring",
    "خايف": "خايف عليك\nKhaayef 3layk\nI'm scared for you",
    "نعسان": "أنا نعسان كتير\nAna na3saan kteer\nI'm very sleepy",
    "جوعان": "أنا جوعان\nAna joo3aan\nI'm hungry",
    "عطشان": "أنا عطشان\nAna 3aTshaan\nI'm thirsty",
    "مؤدّب": "هاد ولد مؤدّب\nHaad walad mu2addab\nThis is a polite boy",
    "مشهور": "هي مغنية مشهورة\nHiyye mughanniye mashhuura\nShe's a famous singer",
    "فخور": "أنا فخور فيك\nAna fakhuur fiik\nI'm proud of you",
    "حامل": "أختي حامل\nEkhti 7aamel\nMy sister is pregnant",
    "ضعيف": "هاد سبب ضعيف\nHaad sabab D3iif\nThis is a weak reason",
    "قلقان": "أنا قلقان عليك\nAna 2al2aan 3layk\nI'm worried about you",
    "جاهز": "الأكل جاهز\nEl-akel jaahez\nThe food is ready",
    "بشع": "الطقس اليوم بشع\nET-Ta2s el-yom bishi3\nThe weather today is ugly",
    "مستعمل": "اشتريت كتاب مستعمل\nEshtarayt kteb musta3mal\nI bought a used book",
    "مْعصّب": "ليش معصّب؟\nLeesh m3a99eb?\nWhy are you angry?",
    "آسف": "آسف عالتأخير\nAasef 3at-ta2khiir\nSorry for the delay",
    "نفس": "نفس الإشي\nNafs el-ishi\nThe same thing",
    "أكيد": "أكيد بدي روح\nAkiid baddi rou7\nFor sure I want to go",
    "عاجل": "هاد شي عاجل\nHaad shi 3aajil\nThis is urgent",
    "كسول": "ليش كسول هيك؟\nLeesh kasuul hayk?\nWhy are you so lazy?",
    "مقرف": "هاي ريحة مقرفة\nHayy rii7a mu2arrfeh\nThis is a disgusting smell",
    "مضحك": "هو كتير مضحك\nHowwe kteer muD7ik\nHe's very funny",
    "مريح": "الكرسي مريح\nEl-kursi muriiH\nThe chair is comfortable",
    "رهيب": "العرض كان رهيب\nEl-3arD kaan rahiib\nThe show was amazing",
    "سيّء": "الجو اليوم سيّء\nEl-jaww el-yom sayye2\nThe weather today is bad",
    "بسيط": "هاد سؤال بسيط\nHaad su2aal basiiT\nThis is a simple question",
    "أساسي": "هاد شرط أساسي\nHaad sharT asaasi\nThis is a basic condition",
    "أعشاب": "بحب شاي بأعشاب\nB7eb shay bi-a3shaab\nI love herbal tea",
    "عالي": "الجبل عالي\nEl-jabal 3aali\nThe mountain is high",
    "واطي": "الصوت واطي\nE9-9ot waaTi\nThe sound is low",
    "كريم": "هو رجال كريم\nHowwe rijjaal kariim\nHe's a generous man",
    "صريح": "كن صريح معي\nKun 9arii7 ma3i\nBe honest with me",
    "لطيف": "هاد ولد لطيف\nHaad walad la6iif\nThis is a nice boy",
    "طيّب": "الأكل طيّب\nEl-akel Tayyeb\nThe food is delicious",
    "حر": "أنا حر اليوم\nAna 7orr el-yom\nI'm free today",
    "لئيم": "ليش لئيم؟\nLeesh la2iim?\nWhy are you mean?",

    # ---------- Adverbs ----------
    "بسرعة": "روح بسرعة!\nRou7 bi-sur3a!\nGo quickly!",
    "بكير": "صحيت بكير\n9e7iit bekkeer\nI woke up early",
    "هلق": "هلق بدي روح\nHalla2 baddi rou7\nNow I want to go",
    "بعدين": "نحكي بعدين\nNe7ki ba3den\nWe'll talk later",
    "دايماً": "دايماً متأخر\nDayman mit2akhkhar\nHe's always late",
    "أبداً": "ما بحب أبداً\nMa b7eb abadan\nI never like it",
    "تقريباً": "تقريباً وصلنا\nTa2riiban w9elna\nWe almost arrived",
    "كمان": "أنا كمان جاي\nAna kamaan jaay\nI'm coming too",
    "خصوصاً": "خصوصاً اليوم\nKho9uu9an el-yom\nEspecially today",
    "حوالي": "حوالي الساعة عشرة\n7awaali es-saa3a 3ashra\nAbout ten o'clock",
    "بالضبط": "بالضبط هيك\nbiD-DabT hayk\nExactly like that",
    "أكيد": "أكيد بييجي\nAkiid byeji\nFor sure he's coming",
    "عموماً": "عموماً، شو رأيك؟\n3umuuman, shu ra2yak?\nGenerally, what do you think?",
    "غالباً": "غالباً بشوفه\nGhaaliban beshufo\nI usually see him",
    "نادراً": "نادراً ما برد\nNaadiran ma berd\nRarely do I reply",
    "أحياناً": "أحياناً بنسى\nA7yaanan bensa\nSometimes I forget",
    "عادةً": "عادةً بأكل عالغدا\n3aadatan baakel 3al-ghada\nUsually I eat at lunch",
    "طبعاً": "طبعاً بدي!\nTab3an baddi!\nOf course I want to!",
    "فجأة": "فجأة إجا عالبيت\nFaj2a ija 3al-bayt\nSuddenly he came home",
    "يمكن": "يمكن بييجي بكرا\nYemkin byeji bukra\nMaybe he'll come tomorrow",
    "بالضبط": "بالضبط زي ما قلت\nbiD-DabT zayy ma 2elt\nExactly like I said",
    "عنجد": "عنجد، ما كنت عارف\n3anjadd, ma kenet 3aaref\nReally, I didn't know",
    "على الأغلب": "على الأغلب بييجي\n3al-aghlab byeji\nProbably he'll come",
    "مع بعض": "نروح مع بعض\nNrou7 ma3 ba3D\nLet's go together",
    "سوا": "بنشتغل سوا\nMneshteghel sawa\nWe work together",
    "لسّا": "لسّا ما جاوب\nLissa ma jaawab\nHe still hasn't answered",
    "مرّتين": "زرتو مرّتين\nZerto marrtein\nI visited him twice",

    # ---------- Time ----------
    "اليوم": "اليوم عندي اجتماع\nEl-yom 3indi ijtimaa3\nToday I have a meeting",
    "بكرا": "بكرا منشوفك\nBukra mnshufak\nTomorrow we'll see you",
    "مبارح": "مبارح كنت تعبان\nMbaare7 kenet ta3baan\nYesterday I was tired",
    "يوم": "اليوم طويل\nEl-yom Tawiil\nThe day is long",
    "أسبوع": "هاد الأسبوع مشغول\nHaad el-usbuu3 mashghuul\nThis week is busy",
    "شهر": "كل شهر بدفع\nKell shahr bdfa3\nEvery month I pay",
    "سنة": "سنة جديدة سعيدة\nSeneh jdiide sa3iide\nHappy new year",
    "ساعة": "بعد ساعة منلتقي\nBa3d saa3a mnelta2i\nAfter an hour we meet",
    "لحظة": "إنطر لحظة\nInTor la7Za\nWait a moment",
    "ثانية": "بس ثانية\nBass thaaniyeh\nJust a second",
    "صبح": "بشرب قهوة الصبح\nBeshrab ahweh e9-9eb7\nI drink coffee in the morning",
    "مسا": "بنام بالمسا\nBnaam bel-masa\nI sleep in the evening",
    "ليل": "الليل هاد طويل\nEl-leyl haad Tawiil\nThis night is long",
    "صيف": "بحب الصيف\nB7eb e9-9ayf\nI love summer",
    "شتا": "بكره الشتا\nBekrah esh-shitaa\nI hate winter",
    "خريف": "بحب جو الخريف\nB7eb jaww el-khariif\nI love autumn weather",
    "ربيع": "الربيع حلو\nEr-rabii3 7elu\nSpring is sweet",
    "ماضي": "ماضي ولا حدا\nMaaDi w-laa 7ada\nThe past is behind",
    "مستقبل": "بفكّر بالمستقبل\nBfakker bel-mustaqbal\nI think about the future",
    "وقت": "ما عندي وقت\nMa 3indi wa2t\nI don't have time",

    # ---------- Numbers ----------
    "واحد": "بدي واحد\nBaddi waa7ad\nI want one",
    "اتنين": "اتنين قهوة\nTneen ahweh\nTwo coffees",
    "تلاتة": "عندي تلاتة\n3indi tlaate\nI have three",
    "أربعة": "أربعة كتب\nArba3a kteb\nFour books",
    "خمسة": "خمسة دقايق\nKhamse da2aaye2\nFive minutes",
    "ستة": "ستة ولاد\nSette wlaad\nSix kids",
    "سبعة": "بشتغل سبع أيام\nBeshteghel sab3 ayyaam\nI work seven days",
    "تمانية": "بنام تمن ساعات\nBnaam tamen saa3aat\nI sleep eight hours",
    "تسعة": "تسعة ناس بالباص\nTes3a naas bel-baa9\nNine people on the bus",
    "إحدعش": "الساعة إحدعش\nEs-saa3a e7da3sh\nIt's eleven o'clock",
    "عشرين": "بدي عشرين دقيقة\nBaddi 3eshriin di2ii2a\nI need twenty minutes",
    "مية": "مية دولار\nMiyye dolar\nA hundred dollars",
    "ألف": "ألف ليرة\nAlf liira\nA thousand pounds",
    "مليون": "مليون شكر\nMilyoon shukr\nA million thanks",

    # ---------- Directions / places ----------
    "شمال": "البيت ع الشمال\nEl-bayt 3a esh-shmaal\nThe house is to the north",
    "جنوب": "السوق ع الجنوب\nEs-soo2 3al januub\nThe market is to the south",
    "شرق": "بنام عا الشرق\nBnaam 3al-shar2\nI sleep on the east",
    "غرب": "الشمس ع الغرب\nEsh-shams 3al-gharb\nThe sun is to the west",
    "يمين": "لف يمين\nLeff yamiin\nTurn right",
    "يسار": "لف يسار\nLeff yasaar\nTurn left",
    "هون": "تعا هون\nTa3a hon\nCome here",
    "هناك": "حطّو هناك\n7eTTo honaak\nPut it there",
    "جوّا": "خلّيها جوّا\nKhalliiha juwwa\nLeave it inside",
    "برّا": "هو برّا\nHowwe barra\nHe's outside",

    # ---------- Prepositions ----------
    "عن": "حكينا عن الشغل\n7akeena 3an esh-shighl\nWe talked about work",
    "فوق": "الكتاب فوق الطاولة\nEl-kteb foo2 eT-Taawleh\nThe book is above the table",
    "بعد": "نحكي بعد ساعة\nNe7ki ba3d saa3a\nWe'll talk in an hour",
    "ضد": "أنا ضد الفكرة\nAna Didd el-fikra\nI'm against the idea",
    "قبل": "قبل ما تروح\n2abel ma trou7\nBefore you go",
    "بين": "بين البيت والشغل\nBayn el-bayt w-esh-shighl\nBetween home and work",
    "تحت": "الكلب تحت السرير\nEl-kalb ta7t es-sariir\nThe dog is under the bed",
    "قدّام": "هو قدّام البيت\nHowwe 2oddaam el-bayt\nHe's in front of the house",
    "جنب": "هو جنب الباب\nHowwe jamb el-baab\nHe's next to the door",
    "خلال": "خلال الأسبوع\nKhilaal el-usbuu3\nDuring the week",
    "من": "أنا من لبنان\nAna min Lebnan\nI'm from Lebanon",
    "إلى": "بدي روح إلى بيروت\nBaddi rou7 ila Bayrut\nI want to go to Beirut",
    "على": "حطّيت الكتاب على الكرسي\n7aTTayt el-kteb 3ala el-kursi\nI put the book on the chair",
    "في": "في ناس كتير\nFi naas kteer\nThere are a lot of people",
    "مع": "إجي معي\nEji ma3i\nCome with me",
    "بدون": "ما بقدر بدونك\nMa b2der bidunak\nI can't without you",
    "كَ": "تصرّف كَ صديق\nT9arraf ka 9adii2\nAct like a friend",
    "زيّ": "هو زيّ أخوي\nHowwe zayy akhuy\nHe's like my brother",
    "غير": "ما بدي غير هاد\nMa baddi ghayr haad\nI don't want anything but this",
    "لَ": "هاي هدية لك\nHayy hadiyye lak\nThis is a gift for you",

    # ---------- Food ----------
    "تفاح": "بحب التفاح\nB7eb et-teffaa7\nI love apples",
    "موز": "اشتريت موز\nEshtarayt mooz\nI bought bananas",
    "خبز": "بشتري خبز كل يوم\nBeshtri khebez kell yom\nI buy bread every day",
    "فطور": "الفطور جاهز\nEl-fTuur jaahez\nBreakfast is ready",
    "جبنة": "بحب جبنة قريشة\nB7eb jebnit 2ariishi\nI love qaresha cheese",
    "دجاج": "بحب أكل الدجاج\nB7eb akel ed-dejaaj\nI love eating chicken",
    "قهوة": "بشرب قهوة الصبح\nBeshrab ahweh e9-9eb7\nI drink coffee in the morning",
    "شاي": "بدك شاي؟\nBaddak shay?\nDo you want tea?",
    "خيار": "بحب خيار بالسلطة\nB7eb khyaar bes-salaTa\nI love cucumber in salad",
    "عجينة": "العجينة جاهزة\nEl-3ajiine jaahzeh\nThe dough is ready",
    "سمك": "أكلنا سمك بالطرابلس\nAkalna samak biT-Traablos\nWe ate fish in Tripoli",
    "طحين": "بدي كيس طحين\nBaddi kiis T7iin\nI need a bag of flour",
    "ثوم": "بحب الثوم بالحمص\nB7eb eth-thuum bil-7omo9\nI love garlic in hummus",
    "عسل": "بشرب شاي بعسل\nBeshrab shay bi-3asal\nI drink tea with honey",
    "خروف": "أكلنا خروف بالعيد\nAkalna kharuuf bel-3iid\nWe ate lamb on Eid",
    "لحمة": "بشتري لحمة طازة\nBeshtri la7meh Taazeh\nI buy fresh meat",
    "حليب": "بدي حليب بالقهوة\nBaddi 7aliib bel-ahweh\nI want milk in the coffee",
    "زيت": "بدي زيت زيتون\nBaddi zait zaytuun\nI want olive oil",
    "زيتون": "بحب الزيتون الأسود\nB7eb ez-zaytuun el-aswad\nI love black olives",
    "بصل": "حطّ بصل بالسلطة\n7eTT ba9al bes-salaTa\nPut onion in the salad",
    "برتقال": "اشتريت برتقال\nEshtarayt burtu2aan\nI bought oranges",
    "بطاطا": "بحب البطاطا المقلية\nB7eb el-baTaaTa el-ma2liyye\nI love fried potatoes",
    "أكل": "الأكل طيب\nEl-akel Tayyeb\nThe food is delicious",
    "أعشاب": "شاي بأعشاب\nShay bi-a3shaab\nHerbal tea",
    "رز": "الرز جاهز\nEr-rozz jaahez\nThe rice is ready",
    "ملح": "بدي شوية ملح\nBaddi shwayyit meleh\nI want a bit of salt",
    "سكّر": "حطّ سكّر بالشاي\n7eTT sukkar besh-shay\nPut sugar in the tea",
    "حلويّات": "بحب الحلويّات\nB7eb el-7alawiyyaat\n I love sweets",
    "شربة": "اعطيني شربة\n2a3Tiini shoraba\nGive me soup",
    "نعنع": "بحب شاي بنعنع\nB7eb shay bi-na3na3\nI love tea with mint",
    "فطر": "الفطر طيب\nEl-feTr Tayyeb\nMushrooms are delicious",
    "بندورة": "بدي بندورة\nBaddi bandoora\nI want tomato",
    "خضراوات": "بحب الخضراوات\nB7eb el-khoDraawaat\nI love vegetables",
    "فواكه": "بشتري فواكه\nBeshtri fawaakeh\nI buy fruits",
    "سلطة": "بدي سلطة\nBaddi salaTa\nI want salad",
    "مي": "كاسة مي من فضلك\nKaaset mayy min faDlak\nA glass of water please",

    # ---------- Family ----------
    "أب": "أبي بالشغل\nAbi besh-shighl\nMy father is at work",
    "أم": "أمي عم تطبخ\nImmi 3am toTbokh\nMy mom is cooking",
    "أخو": "أخوي الكبير\nAkhuy el-kbiir\nMy older brother",
    "أخت": "أختي بدرس\nEkhti btedres\nMy sister is studying",
    "ابن": "ابني عمرو خمسة\nEbni 3umro khamseh\nMy son is five",
    "بنت": "بنتي حلوة\nBenti 7elwe\nMy daughter is sweet",
    "زوج": "زوجي بحبو\nZawji b7ebbo\nI love my husband",
    "زوجة": "زوجتو طيبة\nZawjto Tayybe\nHis wife is kind",
    "أهل": "أهلي بالضيعة\nAhli biD-Day3a\nMy family is in the village",
    "عيلة": "العيلة سوا\nEl-3ayleh sawa\nThe family is together",
    "خال": "خالي صاحب محل\nKhaali 9aa7eb ma7all\nMy uncle owns a shop",
    "عم": "عمي طبيب\n3ammi Tabiib\nMy uncle is a doctor",
    "خالة": "خالتي بحبها\nKhaalti b7ebba\nI love my aunt",
    "عمّة": "عمّتي طبّاخة\n3amti Tabbaakha\nMy aunt is a cook",
    "صديق": "صديقي إجا\n9adii2i ija\nMy friend came",
    "رفيق": "رفيقي بالمدرسة\nRfii2i bel-madraseh\nMy friend is at school",
    "صاحب": "صاحب البيت غالي\n9aa7eb el-bayt ghaali\nThe house owner is nice",
    "طفل": "الطفل عم ينام\nET-Tifel 3am ynaam\nThe child is sleeping",

    # ---------- Body ----------
    "راس": "عم يوجعني راسي\n3am yuuje3ni raasi\nMy head is hurting me",
    "عين": "عيونها زرق\n3yuunha zere2\nHer eyes are blue",
    "وجه": "وجها حلو\nWejhha 7ilu\nHer face is pretty",
    "إيد": "أعطيني إيدك\n2a3Tiini eedak\nGive me your hand",
    "رجل": "رجلي بتوجعني\nRejli btuuje3ni\nMy leg is hurting me",
    "قلب": "قلبي معك\n2albi ma3ak\nMy heart is with you",
    "ظهر": "ظهري بيوجعني\nDhahri byuuje3ni\nMy back hurts",
    "بطن": "بطني فاضي\nbaTni faaDi\nMy stomach is empty",
    "تم": "تمي ما بحكي\nTemmi ma be7ki\nMy mouth doesn't lie",
    "شعر": "شعرها طويل\nSha3rha Tawiil\nHer hair is long",
    "أنف": "أنفي مزكوم\nAnfi mazkuum\nMy nose is congested",
    "منخار": "منخارك مزكوم\nMonkhaarak mazkuum\nYour nose is stuffed",
    "أذن": "أذنه بتوجعو\nIdhno btuuje3o\nHis ear hurts him",
    "سن": "سني بيوجعني\nSenni byuuje3ni\nMy tooth hurts me",
    "كتف": "كتفي تعبان\nKetfi ta3baan\nMy shoulder is tired",
    "صدر": "صدري بيوجعني\n9adri byuuje3ni\nMy chest hurts",
    "إصبع": "كسرت إصبعي\nKasaret e9eb3i\nI broke my finger",
    "لسان": "لسانك حلو\nLsaanak 7ilu\nYour tongue is sweet",
    "زور": "زوري بيوجعني\nZuuri byuuje3ni\nMy throat hurts",
    "رقبة": "رقبتي بتوجعني\nRa2abti btuuje3ni\nMy neck hurts",
    "جسم": "جسمي تعبان\nJesmi ta3baan\nMy body is tired",
    "شفايف": "شفايفك حمراء\nShafaayfak 7amra\nYour lips are red",
    "لحية": "لحيتو طويلة\nLe7yto Tawiile\nHis beard is long",
    "معدة": "معدتي بتوجعني\nMa3edti btuuje3ni\nMy stomach is hurting",

    # ---------- Animals ----------
    "كلب": "عندي كلب صغير\n3indi kalb 9ghiir\nI have a small dog",
    "بسّ": "البسّ بالشباك\nEl-bess besh-shibbaak\nThe cat is at the window",
    "قط": "القط نايم\nEl-2eTT naayem\nThe cat is sleeping",
    "حصان": "ركبت حصان\nRkebet 7e9aan\nI rode a horse",
    "بقرة": "البقرة بتعطي حليب\nEl-ba2ara bta3Ti 7aliib\nThe cow gives milk",
    "جمل": "الجمل بالصحرا\nEl-jamal beS-9a7raa\nThe camel is in the desert",
    "حمار": "الحمار بطيء\nEl-7maar baTii2\nThe donkey is slow",
    "غنمة": "في غنمة بالحقل\nFi ghanameh bel-7a2l\nThere's a sheep in the field",
    "حيّة": "خفت من الحيّة\nKhfet min el-7ayyeh\nI was scared of the snake",
    "فيل": "الفيل كبير\nEl-fiil kbiir\nThe elephant is big",
    "أسد": "الأسد ملك الحيوانات\nEl-asad malek el-7aywaanaat\nThe lion is king of the animals",
    "فار": "في فار بالبيت\nFi faar bel-bayt\nThere's a mouse in the house",
    "بطة": "البطة على المي\nEl-baTTa 3al-mayy\nThe duck is on the water",
    "حمامة": "الحمامة طارت\nEl-7amaameh Taaret\nThe pigeon flew",
    "عصفور": "العصفور بيغني\nEl-3a9fuur byghanni\nThe bird is singing",
    "حيوان": "هاد حيوان لطيف\nHaad 7ayawaan la6iif\nThis is a cute animal",

    # ---------- Colors ----------
    "أحمر": "ورد أحمر\nWard a7mar\nRed flowers",
    "أزرق": "السما زرقا\nEs-sama zar2a\nThe sky is blue",
    "أخضر": "العشب أخضر\nEl-3eshb akhDar\nThe grass is green",
    "أصفر": "الشمس صفرا\nEsh-shams 9afra\nThe sun is yellow",
    "أسود": "كلب أسود\nKalb aswad\nA black dog",
    "أبيض": "بدي قميص أبيض\nBaddi 2amii9 abyaD\nI want a white shirt",
    "زهري": "فستان زهري\nFostaan zahri\nA pink dress",
    "لون": "شو لون السيارة؟\nShu loon es-sayyaara?\nWhat color is the car?",

    # ---------- Common nouns (places, things) ----------
    "بيت": "بيتنا بعيد\nBeitna b3iid\nOur house is far",
    "شغل": "الشغل كتير اليوم\nEsh-shighl kteer el-yom\nWork is a lot today",
    "سيّارة": "سيارتي بالكراج\nSayyaarti bel-karaaj\nMy car is in the garage",
    "مدرسة": "بدرس بالمدرسة\nBedres bel-madraseh\nI study at the school",
    "شمس": "الشمس قوية اليوم\nEsh-shams 2awiyye el-yom\nThe sun is strong today",
    "بحر": "البحر هادي\nEl-ba7r haadi\nThe sea is calm",
    "ناس": "ناس كتير بالسوق\nNaas kteer bes-soo2\nLots of people in the market",
    "ولد": "هاد ولد طيب\nHaad walad Tayyeb\nThis is a kind boy",
    "كتاب": "بقرأ كتاب\nBe2ra kteb\nI'm reading a book",
    "مفتاح": "وين مفتاحي؟\nWen mufte7i?\nWhere is my key?",
    "فلوس": "ما عندي فلوس\nMa 3indi fluus\nI don't have money",
    "مصاري": "صرفت كل مصاريي\n9arafet kell ma9aariyye\nI spent all my money",
    "جسر": "مشينا عالجسر\nMshiina 3al-jisr\nWe walked over the bridge",
    "حديقة": "بنروح عالحديقة\nMnrou7 3al-7adii2a\nWe go to the park",
    "غرفة": "غرفتي صغيرة\nGhurfeti 9ghiire\nMy room is small",
    "مطبخ": "المطبخ نظيف\nEl-maTbakh nDHiif\nThe kitchen is clean",
    "حمّام": "وين الحمّام؟\nWen el-7ammaam?\nWhere is the bathroom?",
    "باب": "سكّر الباب\nSakker el-baab\nClose the door",
    "شبّاك": "افتح الشباك\nIfta7 esh-shibbaak\nOpen the window",
    "كرسي": "اعقد عالكرسي\nE23od 3al-kursi\nSit on the chair",
    "طاولة": "حطّ الأكل عالطاولة\n7eTT el-akel 3aT-Taawleh\nPut the food on the table",
    "تخت": "نمت عالتخت\nNemet 3at-takhet\nI slept on the bed",
    "مفتاح": "ضيّعت المفتاح\nDayya3et el-mufte7\nI lost the key",
    "صحن": "هاد الصحن وسخ\nHaad e9-9a7n wisikh\nThis plate is dirty",
    "كأس": "بدي كأس مي\nBaddi ka2s mayy\nI want a glass of water",
    "معلقة": "بدي معلقة\nBaddi ma3la2a\nI need a spoon",
    "شوكة": "بدي شوكة\nBaddi shookeh\nI want a fork",
    "تليفون": "تلفوني فقدتو\nTelefooni f2adto\nMy phone, I lost it",
    "ساعة": "اشتريت ساعة\nEshtarayt saa3a\nI bought a watch",
    "محفظة": "محفظتي بالشنطة\nMa7faDHti besh-shanTa\nMy wallet is in the bag",
    "شنطة": "شنطتي ثقيلة\nShanTeti tha2iile\nMy bag is heavy",
    "كيس": "ضع المشتريات بكيس\nDa3 el-mushtarayaat bi-kiis\nPut the groceries in a bag",
    "حيط": "علّق الصورة عالحيط\n3alle2 e9-9uura 3al-7eyT\nHang the picture on the wall",
    "ضو": "افتح الضو\nIfta7 eD-Daww\nTurn on the light",
    "غيمة": "في غيوم كتيرة\nFi ghyuum ktiire\nThere are lots of clouds",
    "نجمة": "النجمة بتلمع\nEn-nijmeh btelma3\nThe star shines",
    "قمر": "القمر مدوّر\nEl-2amar mdawwar\nThe moon is round",
    "نار": "اشعل النار\nE3shel en-naar\nLight the fire",
    "هوا": "الهوا بارد\nEl-hawa baared\nThe air is cold",
    "أرض": "الأرض رطبة\nEl-arD raTbeh\nThe ground is wet",
    "سما": "السما زرقا\nEs-sama zar2a\nThe sky is blue",
    "نهر": "النهر طويل\nEn-nahr Tawiil\nThe river is long",
    "جبل": "بنروح عالجبل\nMnrou7 3al-jabal\nWe go to the mountain",
    "صحرا": "السفر بالصحرا تعبان\nEs-safar beS-9a7raa ta3baan\nDesert travel is tiring",
    "غابة": "تهت بالغابة\nTehet bel-ghaabeh\nI got lost in the forest",
    "وادي": "نزلنا عالوادي\nNzelna 3al-waadi\nWe went down to the valley",
    "محيط": "المحيط واسع\nEl-mu7iiT waase3\nThe ocean is wide",
    "خليج": "البحرين عالخليج\nEl-Ba7rayn 3al-khaliij\nBahrain is on the Gulf",
    "جزيرة": "زرت جزيرة\nZeret jaziira\nI visited an island",
    "شارع": "هاد الشارع مزدحم\nHaad esh-shaari3 muzdaa7em\nThis street is crowded",
    "ساحة": "تجمعنا بالساحة\nTjamma3na bes-saa7a\nWe gathered in the square",
    "مدينة": "بيروت مدينة حلوة\nBayrut medineh 7elwe\nBeirut is a nice city",
    "قرية": "ضيعتنا بالجبل\nDay3etna bel-jabal\nOur village is in the mountain",
    "بلد": "بلدي لبنان\nBaladi Lebnan\nMy country is Lebanon",
    "مطار": "المطار بعيد\nEl-maTaar b3iid\nThe airport is far",
    "محطّة": "محطّة الباص\nMa7aTTet el-baa9\nThe bus station",
    "فندق": "حجزت فندق\n7ajazet funduq\nI booked a hotel",
    "مستشفى": "ابني بالمستشفى\nEbni bel-mustashfa\nMy son is at the hospital",
    "مطبخ": "المطبخ بالطابق الأول\nEl-maTbakh biT-Taabe2 el-awwal\nThe kitchen is on the first floor",
    "حديقة": "نمشي بالحديقة\nNemshi bel-7adii2a\nWe walk in the park",
    "مكتب": "مكتبي بالشركة\nMakatbi besh-shirkeh\nMy office is at the company",
    "سوق": "رحت عالسوق\nRe7et 3as-soo2\nI went to the market",
    "دكان": "هاد دكان جديد\nHaad dukkaan jdiid\nThis is a new shop",
    "كنيسة": "صلّينا بالكنيسة\n9allayna bel-kniise\nWe prayed at the church",
    "مسجد": "صلّى بالمسجد\n9alla bel-masjid\nHe prayed at the mosque",
    "متحف": "زرنا المتحف\nZorna el-mat7af\nWe visited the museum",
    "ملعب": "بنلعب بالملعب\nMnel3ab bel-mal3ab\nWe play in the field",
    "مسبح": "سبحنا بالمسبح\nSba7na bel-masba7\nWe swam at the pool",
    "جامعة": "بدرس بالجامعة\nBedres bel-jaami3a\nI study at the university",
    "حياة": "هاي حياتي\nHayy 7ayaati\nThis is my life",
    "حب": "الحب جميل\nEl-7ubb jamiil\nLove is beautiful",
    "بوسة": "اعطيتو بوسة\n2a3Tayto buusa\nI gave him a kiss",
    "أمل": "في أمل\nFi amal\nThere's hope",
    "خوف": "ما تعيش بخوف\nMa t3iish bi-khoof\nDon't live in fear",
    "حزن": "ما يكون فيها حزن\nMa ykuun fiiha 7uzn\nLet there be no sadness in it",
    "غضب": "تجنّب الغضب\nTjannab el-ghaDab\nAvoid anger",
    "أمل": "نعمل بأمل\nNa3mel bi-amal\nWe work with hope",
    "مفاجأة": "كانت مفاجأة حلوة\nKaanet mufaaja2a 7elwe\nIt was a sweet surprise",
    "ضحك": "ضحكنا كتير\nDa7akna kteer\nWe laughed a lot",
    "كلمة": "كلمتك مفيدة\nKilmtak mufiide\nYour word is useful",
    "حكي": "حكي فاضي\n7aki faaDi\nEmpty talk",
    "جواب": "ما عندي جواب\nMa 3indi jawaab\nI don't have an answer",
    "سؤال": "عندي سؤال\n3indi su2aal\nI have a question",
    "قصة": "قصّتو طويلة\n2i99to Tawiile\nHis story is long",
    "خبر": "في خبر منيح\nFi khabar mnii7\nThere's good news",
    "أخبار": "شو الأخبار؟\nShu el-akhbaar?\nWhat's the news?",
    "نكتة": "قال نكتة حلوة\n2aal nukteh 7elwe\nHe told a nice joke",
    "أغنيّة": "غنّى أغنيّة حلوة\nGhanna oghniyyeh 7elwe\nHe sang a nice song",
    "فلم": "شفنا فلم منيح\nShofna filim mneeh\nWe saw a good movie",
    "مسلسل": "بتابع مسلسل\nBtaabe3 musalsal\nI'm following a TV series",
    "هدية": "هاي هدية إلك\nHayy hadiyye elak\nThis is a gift for you",
    "اسم": "شو اسمك؟\nShu esmak?\nWhat's your name?",
    "عمر": "شو عمرك؟\nShu 3umrak?\nHow old are you?",
    "صورة": "صورتك حلوة\n9uurtak 7elwe\nYour picture is nice",
    "كاميرا": "اشتريت كاميرا\nEshtarayt kaamiiraa\nI bought a camera",
    "تلفزيون": "اشتغل التلفزيون\nIshteghel et-televizyon\nThe TV is on",
    "كامبيوتر": "كامبيوتري بطيء\nKaambyuutri baTii2\nMy computer is slow",
    "إيميل": "بعتت إيميل\nBa3atet email\nI sent an email",
    "رسالة": "بعتلي رسالة\nBa3etli risaaleh\nSend me a message",
    "نوع": "شو نوعو؟\nShu noo3o?\nWhat kind is it?",
    "شكل": "هاد شكلو غريب\nHaad shaklo ghariib\nThis looks weird",
    "حجم": "هاد حجم كبير\nHaad 7ajem kbiir\nThis is a big size",
    "قياس": "بدي قياسك\nBaddi 2yaasak\nI need your measurement",
    "وزن": "وزنو خفيف\nWezno khafiif\nIts weight is light",
    "سعر": "شو سعرو؟\nShu si3ro?\nWhat's its price?",
    "حساب": "بدي الحساب\nBaddi el-7isaab\nI want the bill",
    "فاتورة": "ادفع الفاتورة\nEdfa3 el-faatuura\nPay the bill",
    "بنك": "البنك مسكّر\nEl-bank msakkar\nThe bank is closed",
    "مدير": "المدير مشغول\nEl-mudiir mashghuul\nThe manager is busy",
    "موظّف": "أنا موظّف بشركة\nAna muwaDHDHaf bi-shirkeh\nI'm an employee at a company",
    "زبون": "الزبون عالباب\nEz-zbuun 3al-baab\nThe customer is at the door",
    "بياع": "البياع غالي\nEl-bayyaa3 ghaali\nThe seller is generous",
    "سايح": "السايح بيحب الشمس\nEs-saaye7 byi7eb esh-shams\nThe tourist loves the sun",
    "صداع": "عندي صداع\n3indi 9udaa3\nI have a headache",
    "صحة": "صحتك أهم شي\n9e7etak ahamm shi\nYour health is the most important thing",
    "حرارة": "عندو حرارة\n3indo 7araara\nHe has a fever",
    "وجع": "في وجع بظهري\nFi waja3 bi-DHahri\nThere's pain in my back",
    "دوا": "خد الدوا\nKhod ed-dawa\nTake the medicine",
    "علاج": "العلاج طويل\nEl-3ilaaj Tawiil\nThe treatment is long",
    "إبرة": "خفت من الإبرة\nKhfet min el-ibra\nI was scared of the needle",
    "حبّة": "خد حبّة\nKhod 7abbeh\nTake a pill",
    "ريحة": "في ريحة حلوة\nFi rii7a 7elwe\nThere's a nice smell",
    "ضو": "افتح الضو\nIfta7 eD-Daww\nTurn on the light",
    "صوت": "صوتو عالي\n9oto 3aali\nHis voice is loud",
    "ابتسامة": "ابتسامتك حلوة\nIbtisaamtak 7elwe\nYour smile is sweet",
    "موسيقى": "بحب موسيقى هادية\nB7eb muusiiqaa haadyeh\nI love calm music",
    "نظام": "هاد نظام جديد\nHaad niDHaam jdiid\nThis is a new system",
    "خطّة": "عندي خطّة\n3indi khoTTa\nI have a plan",
    "هدف": "هدفي واضح\nHadafi waaDi7\nMy goal is clear",
    "فكرة": "عندي فكرة منيحة\n3indi fikra mnii7a\nI have a good idea",
    "رأي": "شو رأيك؟\nShu ra2yak?\nWhat's your opinion?",
    "قرار": "هاد قراري\nHaad 2araari\nThis is my decision",
    "حلّ": "في حلّ\nFi 7all\nThere's a solution",
    "مشكلة": "في مشكلة كبيرة\nFi mushkleh kbiire\nThere's a big problem",
    "سبب": "ما في سبب\nMa fi sabab\nThere's no reason",
    "غلطة": "هاي غلطتي\nHayy ghal6eti\nThis is my mistake",
    "حقّ": "الحق معك\nEl-7a22 ma3ak\nYou're right",
    "حقيقة": "هاي الحقيقة\nHayy el-7a2ii2a\nThis is the truth",
    "كذبة": "هاي كذبة\nHayy kidhbeh\nThis is a lie",
    "سرّ": "احتفظ بالسرّ\nE7tfeDH bes-serr\nKeep the secret",
    "شكّ": "ما في شكّ\nMa fi shakk\nThere's no doubt",
    "فرصة": "فرصة حلوة\nFur9a 7elwe\nA nice opportunity",
    "حظ": "حظ سعيد!\n7aZZ sa3iid!\nGood luck!",
    "موضوع": "هاد موضوع مهم\nHaad mawDuu3 muhimm\nThis is an important topic",
    "تجربة": "هاي تجربة جديدة\nHayy tajruba jdiide\nThis is a new experience",
    "خبرة": "عندي خبرة\n3indi khibra\nI have experience",
    "مثال": "اعطيني مثال\n2a3Tiini mathaal\nGive me an example",
    "درس": "بحب درس العربي\nB7eb daris el-3arabi\nI love the Arabic lesson",
    "تمرين": "هاد تمرين سهل\nHaad tamriin sahel\nThis is an easy exercise",
    "اختبار": "عندي اختبار بكرا\n3indi ikhtbaar bukra\nI have a test tomorrow",
    "نتيجة": "النتيجة منيحة\nEn-natiije mnii7a\nThe result is good",
    "تقرير": "كتبت التقرير\nKtabet et-ta2riir\nI wrote the report",
    "اجتماع": "عندي اجتماع\n3indi ijtimaa3\nI have a meeting",
    "موعد": "عندي موعد\n3indi maw3id\nI have an appointment",
    "زيارة": "زيارتنا حلوة\nZyaartna 7elwe\nOur visit is nice",
    "رحلة": "رحلة طويلة\nRe7leh Tawiile\nA long trip",
    "مشوار": "بدي روح مشوار\nBaddi rou7 mishwaar\nI want to run an errand",
    "حفلة": "في حفلة\nFi 7afleh\nThere's a party",
    "عرس": "عرس أختي\n3uros okhti\nMy sister's wedding",
    "زواج": "زواجهم قريب\nZawaajhom 2ariib\nTheir marriage is soon",
    "عروس": "العروس حلوة\nEl-3aruus 7elwe\nThe bride is beautiful",
    "عريس": "العريس مبسوط\nEl-3ariis mabsuuT\nThe groom is happy",
    "خطيب": "خطيبي طيب\nKhaTiibi Tayyeb\nMy fiancé is kind",
    "خطيبة": "خطيبتي جميلة\nKhaTiibti jamiile\nMy fiancée is beautiful",
    "هدية": "اشتريت هدية\nEshtarayt hadiyye\nI bought a gift",

    # ---------- Clothes / accessories ----------
    "قميص": "قميصي جديد\n2amii9i jdiid\nMy shirt is new",
    "بنطلون": "بنطلوني وسخ\nBanTalooni wisikh\nMy pants are dirty",
    "فستان": "فستانها حلو\nFostaanha 7ilu\nHer dress is nice",
    "بدلة": "البدلة غالية\nEl-badleh ghaalye\nThe suit is expensive",
    "كندرة": "كندرتي ضايقة\nKundarti Daay2a\nMy shoes are tight",
    "جاكيت": "بدي جاكيت دافي\nBaddi jaakeet daafi\nI want a warm jacket",
    "بلوزة": "بلوزتي وسخة\nBluuzeti wisikha\nMy blouse is dirty",
    "حزام": "ضيّع حزامو\nDayya3 7zaamo\nHe lost his belt",
    "قبّعة": "حطّ قبّعة\n7eTT 2ubba3a\nPut on a hat",
    "خاتم": "خاتمي ضاع\nKhaatmi Daa3\nMy ring is lost",
    "كمّامة": "حطّ كمّامة\n7eTT kammaameh\nPut on a mask",
    "جربان": "جربان مفقود\nJurbaan maf2uud\nA sock is missing",
    "لفحة": "لفحتي دافيي\nLaf7eti daafyeh\nMy scarf is warm",

    # ---------- Demonstratives / pronouns ----------
    "هاد": "هاد بيتي\nHaad bayti\nThis is my house",
    "هاي": "هاي قهوتي\nHayy ahweti\nThis is my coffee",
    "هيك": "ما تعمل هيك\nMa ta3mel hayk\nDon't do it like that",

    # ---------- Misc nouns ----------
    "غيرة": "هاد غيرة فاضية\nHaad ghiira faaDyeh\nThis is pointless jealousy",
    "قائمة": "بدي القائمة\nBaddi el-2aa2ime\nI want the menu",
    "خدمة": "الخدمة منيحة\nEl-khidmeh mnii7a\nThe service is good",
    "صف": "بنروح ع الصف\nMnrou7 3a9-9aff\nWe go to class",
    "طلب": "هاد طلبي\nHaad Talabi\nThis is my order",
    "تأمين": "عندي تأمين\n3indi ta2miin\nI have insurance",
    "محامي": "حكيت مع المحامي\n7akeet ma3 el-mu7aami\nI talked to the lawyer",
    "حكيم": "الحكيم بالمستشفى\nEl-7akiim bel-mustashfa\nThe doctor is at the hospital",
    "طبيب": "أبي طبيب\nAbi Tabiib\nMy father is a doctor",
    "مدرّس": "المدرّس طيب\nEl-mudarres Tayyeb\nThe teacher is kind",
    "مغنّي": "هو مغنّي مشهور\nHowwe mughanniy mashhuur\nHe's a famous singer",
    "زعيم": "هو زعيم البلد\nHowwe za3iim el-balad\nHe's the country's leader",
    "ملك": "الملك بالقصر\nEl-malek bel-2a9er\nThe king is at the palace",
    "ملكة": "الملكة حلوة\nEl-malika 7elwe\nThe queen is pretty",
    "أمير": "الأمير صغير\nEl-amiir 9ghiir\nThe prince is young",
    "أميرة": "الأميرة بكتاب\nEl-amiira bel-kteb\nThe princess in the book",
    "شريك": "هو شريكي\nHowwe shariiki\nHe's my partner",
    "زميل": "زميلي بالشغل\nZamiili besh-shighl\nMy colleague at work",
    "جار": "الجار طيب\nEl-jaar Tayyeb\nThe neighbor is nice",
    "ضيف": "في ضيوف\nFi Dyuuf\nThere are guests",
    "جندي": "هو جندي\nHowwe jundi\nHe's a soldier",
    "شب": "هاد الشب ذكي\nHaad esh-shabb zaki\nThis young man is smart",
    "أجنبي": "هو أجنبي\nHowwe ajnabi\nHe's a foreigner",
    "كرسي": "اقعد عالكرسي\nE23od 3al-kursi\nSit on the chair",
    "صابون": "بدي صابون\nBaddi 9aabuun\nI want soap",
    "محرمة": "اعطيني محرمة\n2a3Tiini ma7rame\nGive me a tissue",
    "مسبحة": "مسبحتو من خشب\nMasba7to min khashab\nHis prayer-beads are wooden",
    "خاتم": "خاتم العرس\nKhaatim el-3ers\nThe wedding ring",
    "مفتاح": "بدي مفتاح جديد\nBaddi mufte7 jdiid\nI need a new key",
    "إيميل": "بعتلي إيميل\nB3etli email\nSend me an email",

    # ---------- Misc useful ----------
    "يلا": "يلا منروح!\nYalla mnrou7!\nLet's go!",
    "خلص": "خلص هلق\nKhala9 halla2\nThat's it now",
    "هلق": "هلق رايح\nHalla2 raaye7\nI'm going now",
    "بطل": "بطل تعمل هيك\nbaTTel ta3mel hayk\nStop doing that",
    "مش": "أنا مش جوعان\nAna mish joo3aan\nI'm not hungry",
}


def main() -> int:
    db_path = Path(sys.argv[1] if len(sys.argv) > 1 else "lebanese.lapse")
    if not db_path.exists():
        print(f"no such file: {db_path}", file=sys.stderr)
        return 1
    conn = sqlite3.connect(db_path, timeout=30.0)

    # Self-migrate if the deck pre-dates schema v4.
    cols = {row[1] for row in conn.execute("PRAGMA table_info(cards)").fetchall()}
    if "example" not in cols:
        conn.execute("ALTER TABLE cards ADD COLUMN example TEXT")
        conn.commit()

    rows = conn.execute(
        "SELECT id, front, back FROM cards WHERE example IS NULL"
    ).fetchall()

    def strip_harakat(s: str) -> str:
        return "".join(c for c in s if c not in "ًٌٍَُِّْـٰ")

    def lookup(ar: str) -> str | None:
        if ar in EXAMPLES:
            return EXAMPLES[ar]
        s = strip_harakat(ar)
        if s != ar and s in EXAMPLES:
            return EXAMPLES[s]
        if s.startswith("ال") and s[2:] in EXAMPLES:
            return EXAMPLES[s[2:]]
        if ("ال" + s) in EXAMPLES:
            return EXAMPLES["ال" + s]
        return None

    updated = 0
    no_match = 0
    for cid, front, back in rows:
        ar = first_arabic_token(front) or first_arabic_token(back)
        if ar is None:
            continue
        ex = lookup(ar)
        if ex is None:
            no_match += 1
            continue
        conn.execute("UPDATE cards SET example = ? WHERE id = ?", (ex, cid))
        updated += 1
    conn.commit()
    conn.close()
    print(f"filled {updated} cards. {no_match} had no matching example.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
